
% clear
% close all
% load mat/read_model.mat m
% m = solve(m); 

% T = 60;
T = 40;
d = sstatedb(m, 1:T);
d.shk_y_gap(1:5) = -1.2;

anticipate = true;

p = Plan.forModel(m, 1:T, "defaultAnticipationStatus", anticipate);
p = swap(p, 1:5, ["y_gap", "shk_y_gap"]);

s0 = simulate(m, d, 1:T, "prependInput", true);


s2 = simulate( ...
    m, d, 1:T ...
    , "prependInput", true ...
    , "method", "stacked" ...
    , "blocks", true ...
    , "initial", "data" ...
    , "anticipate", anticipate ...
    , "solver", {"iris-newton", "skipJacobUpdate", 2} ...
);


s3 = simulate( ...
    m, d, 1:T ...
    , "prependInput", true ...
    , "method", "selective" ...
    , "anticipate", anticipate ...
);

